version: '3.8'

services:

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: ["10"]  # Pass result limit as argument
    working_dir: /tmp
    volumes:
      - ./reports:/tmp/reports  # Host ./reports maps to container /tmp/reports

  db:
    build: db/.
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: world
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
