version: '3.8'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    working_dir: /tmp
    volumes:
      - ./reports:/tmp/reports
    env_file:
      - .env
    environment:
      DB_HOST: db   # override just this one inside Docker

  db:
    build: db/.
    ports:
      - "3306:3306"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s


